[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.27"
verifier = "sourcify"
verifier-url = "https://server-verify.hashscan.io/"


[rpc_endpoints]
hedera="${HEDERA_TN_RPC_URL}"

[etherscan]
296 = { key = "", url = "https://ignore.me" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
